### ISSUE TITLE
missing includes 

### ISSUE THREAD

**Issue by parkstraat9** [ciafe/crankPowerMeter#4]
hello, 

first time I am using arduino IDE, so maybe its my fault.
When I compile the project, It says I am missing 
HX711.h
Adafruit_MPU6050.h

I got HX711,h from https://www.arduino.cc/reference/en/libraries/hx711-arduino-library/

But than it gives me this error. 
```
loadCell.ino: In function 'void load_Setup()':
loadCell.ino:15:14: error: 'class HX711' has no member named 'set_raw_mode'
   loadsensor.set_raw_mode();
              ^

exit status 1

Compilation error: 'class HX711' has no member named 'set_raw_mode'
```

Do I need a other hx711.h?

**Comment by ciafe** [comment]
Hi,

Please use the next hx711 library: https://github.com/RobTillaart/HX711

Best Regards
